name: immich

services:
    immich-server:
        container_name: immich_server
        image: ghcr.io/immich-app/immich-server:release
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USERNAME: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE_NAME: ${DB_NAME}
        ports:
            - "3001:3001"
        volumes:
            - /mnt/immich-photos:/data
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - redis
            - database
        restart: always
        networks:
            - nginxproxymanager_default

    immich-machine-learning:
        container_name: immich_machine_learning
        image: ghcr.io/immich-app/immich-machine-learning:release
        volumes:
            - model-cache:/cache
        restart: always
        networks:
            - nginxproxymanager_default

    immich-microservices:
        container_name: immich_microservices
        image: ghcr.io/immich-app/immich-server:release
        command: ["start-microservices.sh"]
        volumes:
            - /mnt/immich-photos:/data
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - redis
            - database
        restart: always
        networks:
            - nginxproxymanager_default

    immich-web:
        container_name: immich_web
        image: ghcr.io/immich-app/immich-web:release
        ports:
            - "3000:3000"
        depends_on:
            - immich-server
        restart: always
        networks:
            - nginxproxymanager_default

    redis:
        container_name: immich_redis
        image: docker.io/valkey/valkey:8-bookworm
        healthcheck:
            test: redis-cli ping || exit 1
        restart: always
        networks:
            - nginxproxymanager_default

    database:
        container_name: immich_postgres
        image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
        volumes:
            - /mnt/immich-db:/var/lib/postgresql/data
        shm_size: 128mb
        restart: always
        networks:
            - nginxproxymanager_default

volumes:
    model-cache:

networks:
    nginxproxymanager_default:
        external: true
